### ISSUE TITLE
Blend – only remove weight of coating from Urea (Nitrogen product) of the blend

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#1]

**Comment by russgalloway** [comment]
Do you have an example where the weight isn't deducted from the product the coating is assigned to?

If Urea has a coating assigned to it, then the weight of the coating should only be deducted from Urea.  If another product is assigned the blend without a coating, its weight should not be affected.

**Comment by ChongLi** [comment]
Okay, that works
