### ISSUE TITLE
Barge – when a barge is completed and departed, should still be able to see historical information that happened when barge was here.

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#12]
Search history by barge and date range

**Comment by j-hogue** [comment]
This is currently available.

**Comment by ChongLi** [comment]
Not sure how we missed that one, maybe we discussed and didn't actually attempt.  So it looks like in the Barge module, we would select departed status, and barge, and date range?

**Comment by j-hogue** [comment]
You could also use departure date range.
