### ISSUE TITLE
Customer – on Contact set up, what is “Description”?

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#16]

**Comment by russgalloway** [comment]
Description is just an arbitrary label you can give your customer's contacts, i.e. "Office Manager", "Owner", etc.  Would it make more sense to rename that field to "Title" ?

**Comment by ChongLi** [comment]
per Shawna, changing the label to "Title" would be acceptable.

**Comment by j-hogue** [comment]
Completed
