### ISSUE TITLE
Customer/Contract – currently only able to assign Bins here.

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#17]
Should be able to assign Bin initially in the Bin Assignments module as well.  Because one person sets up contract, and a different person is responsible for bin assignment

**Comment by russgalloway** [comment]
We'll fix the bin assignment module so that it also shows contracts that haven't had bins assigned to them yet.

**Comment by j-hogue** [comment]
I this case, create a bin named TBD and assign the contract to it as a default when the bin is unknown at the time the contract is created.  The TBD bin will then show on the bin assignment list.
