### ISSUE TITLE
Customer – Add Contact and Add Contract are easily mistaken for each other

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#18]

**Comment by russgalloway** [comment]
Yes, we agree.  What would you like to call your customer's contacts -- would "employees" work?

**Comment by ChongLi** [comment]
man, "employees" worked, but not as expected... Shawna dislikes that suggestion so much that she can live with it the way it is currently, will just take some getting used to.

Also, I googled synonyms for contact, and google had #1 answer as "touch"... that just doesn't sound right.
