### ISSUE TITLE
Customer – What are Rail Rate Adjustment and Harbor Rate Adjustment?

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#19]
They are currently required, can they be defaulted to 0.

**Comment by j-hogue** [comment]
Allows increasing or decreasing Harbor Fleeting Rates or Rail Storage Rates per customer. Example charge XYZ Customer 10% more per day for Rail Car storage.

**Comment by ChongLi** [comment]
that would work fine,  please set initial value to zero for those.  It only saves a second on setup, but at least that way, ones who never need it won't even notice its there when setting up customers.

**Comment by j-hogue** [comment]
I added some helper text to explain the fields better, as well as defaulted to zero.
