### ISSUE TITLE
Barge - What is Rate Effective Date?

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#2]

**Comment by russgalloway** [comment]
Rate Effective Date allows the user to override which rates to apply to a barge.  Say, for example, the fleeting rates were $35/day in December 2017 and changed to $40/day January 1st, 2018.  If a barge arrives January 1st but you wanted to charge them based the prior rate, you would enter December 31st 2017 as the Rate Effective Date -- which is a date that falls within the range of when the $35/day rate was applicable.

**Comment by ChongLi** [comment]
Gotcha
