### ISSUE TITLE
Customer – Account # - this is a required field currently, but has to be entered by the user.

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#20]
Should be auto generated? …Need clarification on this, how do we want it to work.  We will need an account #, just not at setup.  We will fill in later.  Let’s see what Patrick has to say about that.

**Comment by russgalloway** [comment]
This is the accounting number at the Bruce Oakley home office that we'll send with the invoice datafile.  It needs to be entered by the user before billing can be processed.

We can make it not required to create a customer record, but we'll need to stop the billing process if there are any charges for a customer without a proper account number.

**Comment by ChongLi** [comment]
Okay, so it is the account number from Sage 100  (Bruce Oakley home office accounting system).  I think in many cases a customer is set up in the system prior to being set up in MAS, so they have to go add the account number later.

**Comment by j-hogue** [comment]
Completed
