### ISSUE TITLE
Contract – Rate setup, the lower limit and upper limit together are known should be labeled as guaranteed minimum

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#21]

**Comment by russgalloway** [comment]
I'm not sure we fully understand this one -- need to discuss further.

**Comment by sanderson2556** [comment]
This is basically a tier rate.  Once a fert customer reaches their guaranteed minimum (i.e. 0 nt to 60,000 nt @ $9.00/nt, then 60,001 nt @ $6.00/nt thereafter) then their rate goes down.

**Comment by j-hogue** [comment]
I am not sure what `Label` we are talking about.  Are you wanting a Rate named `Guaranteed Minimum Inbound Handling` and `Guaranteed Minimum Outbound Handling`?

**Comment by sanderson2556** [comment]
I’m going to talk with Eric and he’ll get back to you.

**Comment by ChongLi** [comment]
I got some clarification from Shawna on this question, Jack, give me a call because I believe it would be easier to explain over the phone vs writing it down initially.  Once we talk, then I'll figure out the best way to document here.

**Comment by j-hogue** [comment]
Added Guaranteed Minimum Tons to the customers contract.

**Comment by sanderson2556** [comment]
Yes you did.  But how does that apply to the ‘Add Rate’ section where it determines how to bill the tier rate?

**Comment by j-hogue** [comment]
The Guaranteed Minimum if set will be taken into account using the rate chart during billing.

If a customers Guaranteed Minimum is 200 tons, and you have a Rate that goes from 0 tons to 200 tons and the customer only loads out 150 tons, we will use the rate that applies to the range of loaded tons to charge them the additional 50 tons. This method could also span rates.  For example Rate from 0 - 100 tons @5.00 per ton and another rate from 101 - 200 tons @ 10.00 per ton.  They system will charge the first 100 tons @5.00 and then charge the other 50 tons @10.00 and the remaining 50 tons to meet the Guaranteed Minimum @10.00 per ton.
