### ISSUE TITLE
Scale – need to be able to search Driver and Carrier, the old system already has this ability, don’t want to lose it.

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#24]

**Comment by russgalloway** [comment]
This can be done by clicking the magnifying glass icon next to the driver name field.  

We put this functionality in a popup dialog because it gave us a way to show more detail about the driver you're searching for than what we could show if we had made the driver name box an auto-complete widget.

The driver search dialog allows the scale operator to search by drive name, license #, carrier name, tractor and trailer.

**Comment by j-hogue** [comment]
Change: The driver search dialog allows the scale operator to search by drive name only.

**Comment by j-hogue** [comment]
Completed Redesign
