### ISSUE TITLE
Scale – What is the scenario where the “Save” button is needed instead of “Check In”

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#25]
...remember hearing this explained in meeting, but need refresher

**Comment by russgalloway** [comment]
This allows a scale operator to save their process during a check-in -- for instance, after they've already entered the driver's info but for whatever reason needed to move the truck off the scales. 
 Saving without checking-in lets them close the order and resume the check-in later without loosing their progress.

**Comment by j-hogue** [comment]
Completed
