### ISSUE TITLE
Scale – Will BOL automatically print (3 copies) when “check out” clicked?

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#28]

**Comment by russgalloway** [comment]
Yet -- it'll print as many copies as you need -- once we get into creating the printable "reports".

**Comment by j-hogue** [comment]
Completed

**Comment by ChongLi** [comment]
the question was more about just automatically printing the 3 copies to the printer, without any "click to print" button needed.  Its cool that it's not functioning yet.
