### ISSUE TITLE
System Setup – Lot & Pad – these are separate objects in setup, but could be changed to single object called “Lot/Pad”.

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#32]
They are the same thing, just different terminology depending on industry.

**Comment by russgalloway** [comment]
We thought we had hashed this out a while back and decided to make lots and pads independent concepts, but if that's no longer the case, we can drop Pads and relabel "Lot" to "Lot/Pad".

If will end up being quite a few changes if we remove pads, so we just wanted to make sure this is really what you need first.

**Comment by ChongLi** [comment]
Yes, that works.  believe they are more comfortable having "Lot/Pad" as a single object

**Comment by sanderson2556** [comment]
Who is ChongLi and why is he in our discussion?  Eric is there a side of you I don't want to know about???

**Comment by j-hogue** [comment]
Merged Lot and Pad into Lot/Pad. Completed
