### ISSUE TITLE
Barge/Add Cargo – Inbound Tons – is this supposed to be origin weight?

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#6]
When transferring cargo from barge to inventory, if transferred tons is greater than Inbound Tons, the net negative shows up in Tons On Hand.  Should show 0 and change barge status to Empty

**Comment by russgalloway** [comment]
Yes, inbound tons is the origin weight.  We can change the label to say "Origin Weight" if you like.

To clarify, you want the ability to transfer more tonnage to an inventory than the barge's origin weight tonnage, but instead of showing the true negative amount that the transfer creates on the barge's inbound cargo, you'd like to see 0?

How about when the inbound cargo is transferred to an inventory, if the amount is greater than than the origin weight, we deduct the actual amount transferred from the barge, but also automatically create a zero adjustment record to bring the barge's inventory back to 0.  That way the actual inventory amounts are retained and the on-hand amounts can still be calculated normally.

**Comment by j-hogue** [comment]
Changed Inbound label to Origin.

**Comment by ChongLi** [comment]
I think this will work, will verify with everyone
