### ISSUE TITLE
Barge – Barge status needs to be independent of charges/movements.

### ISSUE THREAD

**Issue by russgalloway** [etsinc/boi-boss#9]

**Comment by russgalloway** [comment]
The logic for determining what status a barge is in was to remove the ability to mistakenly assign the wrong status to a barge.

Regarding #6, we can also add logic to display either "Loaded" or "Empty" alongside the current status.  That way you can know the cargo/inventory state independent of what other status you consider the barge to be in at any given time.

**Comment by j-hogue** [comment]
Added Cargo state to Barge and Rail Cars.
